#pragma once

#define TIMER_THREAD_DISPLAYER 0x0921

#define RAVID_TIMER_DEVICEBASE		0X100000
#define RAVID_TIMER_CAMERA		RAVID_TIMER_DEVICEBASE + 1
#define RAVID_TIMER_COMM		RAVID_TIMER_CAMERA + 1
#define RAVID_TIMER_DIO			RAVID_TIMER_COMM + 1
#define RAVID_TIMER_MOTION		RAVID_TIMER_DIO + 1
#define RAVID_TIMER_TRIGGER		RAVID_TIMER_MOTION + 1